name: Check Website Links

on:
  schedule:
    - cron: "0 10 * * 1" # Every Monday at 10:00 AM UTC

jobs:
  check-links:
    name: Check Links in Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # pin@v3

      - name: Build and Run
        run: docker build -t check-links .
